"""Stockfish wrapper for generating training labels."""

from dataclasses import dataclass

import chess
from stockfish import Stockfish as StockfishEngine


@dataclass
class StockfishLabel:
    """Labels generated by Stockfish for a position."""
    best_move: chess.Move
    evaluation: float  # centipawn evaluation normalized to [-1, 1]
    depth: int


class StockfishLabeler:
    """Generate training labels from Stockfish analysis."""

    def __init__(self, path: str = "", depth: int = 16):
        """Initialize Stockfish engine.

        Args:
            path: Path to Stockfish binary. Empty string uses default from pip package.
            depth: Search depth for analysis.
        """
        params = {"Threads": 1, "Hash": 64}
        if path:
            self.engine = StockfishEngine(path=path, depth=depth, parameters=params)
        else:
            self.engine = StockfishEngine(depth=depth, parameters=params)
        self.depth = depth

    def label(self, board: chess.Board) -> StockfishLabel | None:
        """Generate labels for a position.

        Args:
            board: Position to analyze.

        Returns:
            StockfishLabel or None if position is terminal.
        """
        if board.is_game_over():
            return None

        self.engine.set_fen_position(board.fen())

        best_move_uci = self.engine.get_best_move()
        if best_move_uci is None:
            return None

        best_move = chess.Move.from_uci(best_move_uci)

        evaluation = self.engine.get_evaluation()
        eval_score = self._normalize_eval(evaluation, board.turn)

        return StockfishLabel(
            best_move=best_move,
            evaluation=eval_score,
            depth=self.depth,
        )

    def label_batch(self, boards: list[chess.Board]) -> list[StockfishLabel | None]:
        """Generate labels for multiple positions."""
        return [self.label(board) for board in boards]

    @staticmethod
    def _normalize_eval(evaluation: dict, turn: chess.Color) -> float:
        """Normalize Stockfish evaluation to [-1, 1] from side-to-move perspective.

        Args:
            evaluation: Stockfish evaluation dict with 'type' and 'value'.
            turn: Side to move.

        Returns:
            Normalized evaluation in [-1, 1].
        """
        eval_type = evaluation["type"]
        value = evaluation["value"]

        if eval_type == "mate":
            # Mate in N moves: sign indicates who is winning
            return 1.0 if value > 0 else -1.0

        # Centipawn evaluation: use tanh-like normalization
        # Scale so that +300cp ≈ 0.75, +600cp ≈ 0.95
        import math
        normalized = math.tanh(value / 400.0)
        return normalized

    def close(self):
        """Shut down the engine."""
        del self.engine
